services:
  - type: web
    name: dailyintegral
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: NODE_VERSION
        value: "20"
