"""
Curated pool of genuinely challenging integrals (sourced from the user's links
+ classics), each verified by the strengthened NewProblem.verify():
  - indefinite: d/dx(solution) == integrand
  - definite:   value == mpmath numeric quadrature (or trusted symbolic)

Candidates may supply a hand-authored `solution` (for SymPy-stumpers or to
replace an ugly auto-form). `trusted=True` marks textbook definite integrals
whose numeric quadrature does not converge (e.g. Dirichlet).
"""

CANDIDATES: list[dict] = [
    # ══ Advanced Rational Functions (quartic+ denominators) ════════════════════
    {"isrc": "1/(1+x**4)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Divide numerator and denominator ideas aside: factor $x^4+1=(x^2-\sqrt2 x+1)(x^2+\sqrt2 x+1)$",
               r"Use partial fractions over the two irreducible quadratics",
               r"Each piece yields an $\arctan$ plus a $\ln$ term"]},
    {"isrc": "x**2/(1+x**4)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^4+1=(x^2-\sqrt2 x+1)(x^2+\sqrt2 x+1)$",
               r"Partial fractions; the symmetry of $x^2$ in the numerator simplifies the work"]},
    {"isrc": "(1+x**2)/(1+x**4)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Divide top and bottom by $x^2$: $\frac{1+1/x^2}{x^2+1/x^2}$",
               r"Substitute $u=x-\frac{1}{x}$, so $du=(1+1/x^2)dx$ and $x^2+1/x^2=u^2+2$"]},
    {"isrc": "(1-x**2)/(1+x**4)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Divide top and bottom by $x^2$",
               r"Substitute $u=x+\frac{1}{x}$, giving $x^2+1/x^2=u^2-2$"]},
    {"isrc": "1/(1+x**6)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^6+1=(x^2+1)(x^4-x^2+1)$",
               r"Decompose into partial fractions over the quadratic factors"]},
    {"isrc": "1/(1+x**3)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^3+1=(x+1)(x^2-x+1)$",
               r"Partial fractions: $\frac{A}{x+1}+\frac{Bx+C}{x^2-x+1}$",
               r"Complete the square in the quadratic term for the $\arctan$"]},
    {"isrc": "1/(x**4-1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^4-1=(x-1)(x+1)(x^2+1)$",
               r"Partial fractions give two logs and one $\arctan$"]},
    {"isrc": "x/(1+x**4)", "topic": "Advanced Rational Functions", "difficulty": "medium",
     "hints": [r"Substitute $u=x^2$, $du=2x\,dx$",
               r"Reduces to $\frac{1}{2}\int\frac{du}{1+u^2}=\frac{1}{2}\arctan(x^2)$"]},
    {"isrc": "1/(x**4+x**2+1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^4+x^2+1=(x^2-x+1)(x^2+x+1)$",
               r"Partial fractions over the two quadratics"]},
    {"isrc": "1/(x**6-1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^6-1=(x-1)(x+1)(x^2+x+1)(x^2-x+1)$",
               r"Decompose into partial fractions"]},
    {"isrc": "1/(x**4-x**2+1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^4-x^2+1=(x^2-\sqrt3 x+1)(x^2+\sqrt3 x+1)$",
               r"Partial fractions over the irreducible quadratics"]},
    {"isrc": "x**2/(x**6+1)", "topic": "Advanced Rational Functions", "difficulty": "medium",
     "hints": [r"Substitute $u=x^3$, $du=3x^2 dx$",
               r"Reduces to $\frac{1}{3}\arctan(x^3)$"]},
    {"isrc": "x**4/(x**6+1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Note $\frac{x^4}{x^6+1}$; factor $x^6+1=(x^2+1)(x^4-x^2+1)$",
               r"Partial fractions over the factors"]},
    {"isrc": "1/(x**3-1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^3-1=(x-1)(x^2+x+1)$",
               r"Partial fractions, then complete the square for the $\arctan$"]},
    {"isrc": "(x**2+1)/(x**4-x**2+1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Divide top and bottom by $x^2$",
               r"Substitute $u=x-\frac1x$; the answer is the neat $\arctan(x)+\arctan(x^3)$"]},
    {"isrc": "x/(x**4+x**2+1)", "topic": "Advanced Rational Functions", "difficulty": "medium",
     "hints": [r"Substitute $u=x^2$, $du=2x\,dx$",
               r"Reduces to $\frac{1}{2}\int\frac{du}{u^2+u+1}$; complete the square"]},
    {"isrc": "1/(x**2+1)**3", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Use the reduction formula for $\int\frac{dx}{(x^2+1)^n}$",
               r"Or substitute $x=\tan\theta$ and integrate $\cos^4\theta$"]},
    {"isrc": "1/(x**2+1)**2", "topic": "Advanced Rational Functions", "difficulty": "medium",
     "hints": [r"Substitute $x=\tan\theta$; the integral becomes $\int\cos^2\theta\,d\theta$",
               r"Use the half-angle identity, then convert back"]},
    {"isrc": "x**2/(x**2+1)**2", "topic": "Advanced Rational Functions", "difficulty": "medium",
     "hints": [r"Write $\frac{x^2}{(x^2+1)^2}=\frac{1}{x^2+1}-\frac{1}{(x^2+1)^2}$",
               r"Integrate each term"]},
    {"isrc": "x**3/(x**2+1)**2", "topic": "Advanced Rational Functions", "difficulty": "medium",
     "hints": [r"Substitute $u=x^2+1$, so $x^3 dx=\frac{(u-1)}{2}du$",
               r"Split into $\frac{1}{2}\int(\frac{1}{u}-\frac{1}{u^2})du$"]},
    {"isrc": "1/(x**4+1)**3", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"A high-order power of an irreducible quartic — use repeated reduction",
               r"The rational part dominates; expect a long but elementary answer"]},
    {"isrc": "(x**2-3*x+1)/(x**4+x**2+1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^4+x^2+1=(x^2-x+1)(x^2+x+1)$",
               r"The numerator splits cleanly across the two quadratics — no leftover integrals needed"]},
    {"isrc": "(x**6-x**5-x+1)/(x**8+x**4+1)", "topic": "Advanced Rational Functions", "difficulty": "hard",
     "hints": [r"Factor $x^8+x^4+1=(x^4-x^2+1)(x^4+x^2+1)$",
               r"Group the numerator to match the factorization and simplify"]},

    # ══ Clever / Designed Integrals ════════════════════════════════════════════
    {"isrc": "(x+sp.sin(x))/(1+sp.cos(x))", "topic": "Clever Manipulation", "difficulty": "hard",
     "hints": [r"Use $1+\cos x=2\cos^2\frac{x}{2}$ and $\sin x=2\sin\frac x2\cos\frac x2$",
               r"The expression collapses to $\frac{x}{2}\sec^2\frac x2+\tan\frac x2$",
               r"Recognize $\frac{d}{dx}\left(x\tan\frac x2\right)$ — the answer is just $x\tan\frac{x}{2}$"]},
    {"isrc": "sp.acot(x**2-x+1)", "topic": "Clever Manipulation", "difficulty": "hard",
     "hints": [r"Integrate by parts with $u=\operatorname{arccot}(x^2-x+1)$, $dv=dx$",
               r"Note $x^2-x+1=x(x-1)+1$ hints at an $\arctan$ subtraction identity"]},
    {"isrc": "(x**2+x)/(sp.exp(x)+x+1)**2", "topic": "Clever Manipulation", "difficulty": "hard",
     "hints": [r"Let $D=e^x+x+1$, so $D'=e^x+1$",
               r"Look for a quotient $\frac{f(x)}{D}$ whose derivative is the integrand",
               r"Try differentiating $\frac{x+1}{e^x+x+1}$ and compare"]},

    # ══ Hand-authored: SymPy gives an unusable form ════════════════════════════
    {"isrc": "1/(1+sp.sin(x)**2)", "solution": r"\frac{\arctan(\sqrt{2}\tan(x))}{\sqrt{2}} + C",
     "topic": "Trigonometric Rational", "difficulty": "hard",
     "hints": [r"Divide numerator and denominator by $\cos^2 x$",
               r"Get $\frac{\sec^2 x}{\sec^2 x+\tan^2 x}=\frac{\sec^2 x}{1+2\tan^2 x}$",
               r"Substitute $u=\tan x$, $du=\sec^2 x\,dx$, then integrate $\frac{1}{1+2u^2}$"]},

    # ══ Trigonometric Rational (Weierstrass) ═══════════════════════════════════
    {"isrc": "1/(sp.sin(x)+sp.cos(x))", "topic": "Trigonometric Rational", "difficulty": "hard",
     "hints": [r"Write $\sin x+\cos x=\sqrt2\sin(x+\tfrac\pi4)$",
               r"Or use the Weierstrass substitution $t=\tan\frac x2$"]},
    {"isrc": "1/(1+sp.tan(x))", "topic": "Trigonometric Rational", "difficulty": "hard",
     "hints": [r"Write $\frac{1}{1+\tan x}=\frac{\cos x}{\cos x+\sin x}$",
               r"Express the numerator as a combination of the denominator and its derivative"]},
    {"isrc": "1/(2+sp.cos(x))", "solution": r"\frac{2}{\sqrt{3}}\arctan\left(\frac{\tan(\frac{x}{2})}{\sqrt{3}}\right) + C",
     "topic": "Trigonometric Rational", "difficulty": "hard",
     "hints": [r"Weierstrass substitution $t=\tan\frac x2$: $\cos x=\frac{1-t^2}{1+t^2}$, $dx=\frac{2\,dt}{1+t^2}$",
               r"Reduces to $\int\frac{2\,dt}{t^2+3}$, an $\arctan$"]},
    {"isrc": "1/(5+4*sp.cos(x))", "solution": r"\frac{2}{3}\arctan\left(\frac{\tan(\frac{x}{2})}{3}\right) + C",
     "topic": "Trigonometric Rational", "difficulty": "hard",
     "hints": [r"Weierstrass $t=\tan\frac x2$",
               r"Denominator becomes proportional to $t^2+9$; the result is $\frac{2}{3}\arctan\frac{t}{3}$"]},
    {"isrc": "1/(3+5*sp.cos(x))", "topic": "Trigonometric Rational", "difficulty": "hard",
     "hints": [r"Weierstrass $t=\tan\frac x2$; here $3+5\cos x$ gives a hyperbolic/log form",
               r"The denominator factors over the reals, yielding a logarithm"]},
    {"isrc": "sp.cos(x)/(1+sp.sin(x)**2)", "topic": "Trigonometric Rational", "difficulty": "medium",
     "hints": [r"Substitute $u=\sin x$, $du=\cos x\,dx$",
               r"Reduces to $\int\frac{du}{1+u^2}=\arctan(\sin x)$"]},

    # ══ High-Power Trigonometric ═══════════════════════════════════════════════
    {"isrc": "sp.sin(x)**5", "topic": "Trigonometric Powers", "difficulty": "medium",
     "hints": [r"Save one $\sin x$: $\sin^5 x=(1-\cos^2 x)^2\sin x$",
               r"Substitute $u=\cos x$"]},
    {"isrc": "sp.cos(x)**5", "topic": "Trigonometric Powers", "difficulty": "medium",
     "hints": [r"Save one $\cos x$: $\cos^5 x=(1-\sin^2 x)^2\cos x$",
               r"Substitute $u=\sin x$"]},
    {"isrc": "sp.sin(x)**6", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Use $\sin^2 x=\frac{1-\cos 2x}{2}$ and cube it",
               r"Apply power reduction repeatedly to the resulting $\cos^2 2x$, $\cos^3 2x$ terms"]},
    {"isrc": "sp.cos(x)**6", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Use $\cos^2 x=\frac{1+\cos 2x}{2}$ and cube it",
               r"Reduce each resulting power until everything is linear in cosines"]},
    {"isrc": "sp.sin(x)**7", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Odd power: $\sin^7 x=(1-\cos^2 x)^3\sin x$",
               r"Substitute $u=\cos x$ and expand $(1-u^2)^3$"]},
    {"isrc": "sp.cos(x)**7", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Odd power: $\cos^7 x=(1-\sin^2 x)^3\cos x$",
               r"Substitute $u=\sin x$"]},
    {"isrc": "sp.tan(x)**4", "topic": "Trigonometric Powers", "difficulty": "medium",
     "hints": [r"$\tan^4 x=\tan^2 x(\sec^2 x-1)$",
               r"Integrate $\tan^2 x\sec^2 x$ by $u=\tan x$, and reuse $\tan^2 x=\sec^2 x-1$"]},
    {"isrc": "sp.tan(x)**5", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"$\tan^5 x=\tan^3 x(\sec^2 x-1)$",
               r"Peel off $\sec^2 x$ factors, substituting $u=\tan x$ each time"]},
    {"isrc": "sp.tan(x)**6", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Repeatedly apply $\tan^2 x=\sec^2 x-1$",
               r"Each step lowers the power and produces an integrable $\tan^k x\sec^2 x$"]},
    {"isrc": "sp.sec(x)**3", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Integrate by parts with $u=\sec x$, $dv=\sec^2 x\,dx$",
               r"The integral reappears; solve algebraically",
               r"Answer involves $\frac12\sec x\tan x+\frac12\ln|\sec x+\tan x|$"]},
    {"isrc": "sp.sec(x)**5", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Reduction formula for $\int\sec^n x\,dx$",
               r"Reduces $\sec^5\to\sec^3\to\sec$"]},
    {"isrc": "sp.sec(x)**6", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Even power: save $\sec^2 x\,dx$ and write the rest as $(1+\tan^2 x)^2$",
               r"Substitute $u=\tan x$"]},
    {"isrc": "sp.csc(x)**4", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Save $\csc^2 x\,dx$ and write $\csc^2 x=1+\cot^2 x$",
               r"Substitute $u=\cot x$, $du=-\csc^2 x\,dx$"]},
    {"isrc": "sp.cot(x)**3", "topic": "Trigonometric Powers", "difficulty": "medium",
     "hints": [r"$\cot^3 x=\cot x(\csc^2 x-1)$",
               r"Substitute $u=\cot x$ for the first part; the second is $\int\cot x\,dx=\ln|\sin x|$"]},
    {"isrc": "sp.cot(x)**4", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"$\cot^4 x=\cot^2 x(\csc^2 x-1)$, and $\cot^2 x=\csc^2 x-1$",
               r"Substitute $u=\cot x$ where $\csc^2 x$ appears"]},
    {"isrc": "sp.sin(x)**2*sp.cos(x)**2", "topic": "Trigonometric Powers", "difficulty": "medium",
     "hints": [r"Use $\sin x\cos x=\frac12\sin 2x$, so the integrand is $\frac14\sin^2 2x$",
               r"Apply power reduction to $\sin^2 2x$"]},
    {"isrc": "sp.sin(x)**4*sp.cos(x)**2", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"Write in terms of double angles via power-reduction identities",
               r"Or use $\sin^4 x\cos^2 x=\sin^2 x(\sin x\cos x)^2$"]},
    {"isrc": "sp.sin(x)**3*sp.cos(x)**4", "topic": "Trigonometric Powers", "difficulty": "medium",
     "hints": [r"Odd power of sine: $\sin^3 x=(1-\cos^2 x)\sin x$",
               r"Substitute $u=\cos x$"]},
    {"isrc": "sp.sin(x)**4*sp.cos(x)**4", "topic": "Trigonometric Powers", "difficulty": "hard",
     "hints": [r"$\sin^4 x\cos^4 x=\frac{1}{16}\sin^4 2x$",
               r"Apply power reduction to $\sin^4 2x$"]},

    # ══ Inverse Trig & Log (by parts / clever) ═════════════════════════════════
    {"isrc": "x*sp.asin(x)", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"By parts: $u=\arcsin x$, $dv=x\,dx$",
               r"The leftover $\int\frac{x^2}{\sqrt{1-x^2}}dx$ needs $x=\sin\theta$ or a clever split"]},
    {"isrc": "x*sp.asin(x)/sp.sqrt(1-x**2)", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arcsin x$, $dv=\frac{x}{\sqrt{1-x^2}}dx$",
               r"Then $v=-\sqrt{1-x^2}$ and the leftover integral is elementary"]},
    {"isrc": "x**2*sp.atan(x)", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arctan x$, $dv=x^2 dx$",
               r"The leftover $\int\frac{x^3}{1+x^2}dx$ needs polynomial division"]},
    {"isrc": "x**2*sp.asin(x)", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arcsin x$, $dv=x^2 dx$",
               r"Leftover $\int\frac{x^3}{\sqrt{1-x^2}}dx$ via $u=1-x^2$"]},
    {"isrc": "x*sp.acos(x)", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"By parts: $u=\arccos x$, $dv=x\,dx$",
               r"Then handle $\int\frac{x^2}{\sqrt{1-x^2}}dx$"]},
    {"isrc": "x**2*sp.acos(x)", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arccos x$, $dv=x^2 dx$",
               r"Leftover $\int\frac{x^3}{\sqrt{1-x^2}}dx$ via $u=1-x^2$"]},
    {"isrc": "sp.asin(x)**2", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arcsin^2 x$, $dv=dx$, so $v=x$",
               r"Leftover $\int\frac{2x\arcsin x}{\sqrt{1-x^2}}dx$ — parts again"]},
    {"isrc": "x*sp.atan(x)", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"By parts: $u=\arctan x$, $dv=x\,dx$",
               r"Leftover $\int\frac{x^2}{1+x^2}dx=\int(1-\frac{1}{1+x^2})dx$"]},
    {"isrc": "sp.atan(x)/(1+x**2)", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"Substitute $u=\arctan x$, $du=\frac{dx}{1+x^2}$",
               r"Integral becomes $\int u\,du=\frac{\arctan^2 x}{2}$"]},
    {"isrc": "sp.atan(sp.sqrt(x))", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arctan\sqrt x$, $dv=dx$",
               r"Then $du=\frac{1}{2\sqrt x(1+x)}dx$; the leftover integral is rational in $\sqrt x$"]},
    {"isrc": "sp.asin(sp.sqrt(x))", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arcsin\sqrt x$, $dv=dx$",
               r"Then handle $\int\frac{\sqrt x}{\sqrt{1-x}}\cdot\frac{1}{2\sqrt x}dx$"]},
    {"isrc": "sp.atan(x)/x**2", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\arctan x$, $dv=x^{-2}dx$, so $v=-\frac1x$",
               r"Leftover $\int\frac{1}{x(1+x^2)}dx$ via partial fractions"]},
    {"isrc": "sp.log(1+x**2)", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"By parts: $u=\ln(1+x^2)$, $dv=dx$",
               r"Leftover $\int\frac{2x^2}{1+x^2}dx=2\int(1-\frac{1}{1+x^2})dx$"]},
    {"isrc": "x*sp.log(1+x**2)", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"Substitute $u=1+x^2$ first, or parts with $dv=x\,dx$",
               r"Reduces to $\frac12\int\ln u\,du$"]},
    {"isrc": "sp.log(x**2+1)/x**2", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts: $u=\ln(x^2+1)$, $dv=x^{-2}dx$",
               r"Leftover $\int\frac{2}{1+x^2}dx=2\arctan x$"]},
    {"isrc": "sp.sin(sp.log(x))", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"By parts twice (or substitute $x=e^t$ to get $\int e^t\sin t\,dt$)",
               r"The original integral reappears; solve algebraically"]},
    {"isrc": "sp.cos(sp.log(x))", "topic": "Inverse Trig & Log", "difficulty": "hard",
     "hints": [r"Substitute $x=e^t$: integral becomes $\int e^t\cos t\,dt$",
               r"Integrate by parts twice and solve for the integral"]},
    {"isrc": "x**4*sp.log(x)", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"By parts: $u=\ln x$, $dv=x^4 dx$",
               r"Then $v=\frac{x^5}{5}$ and the leftover is a power"]},
    {"isrc": "sp.log(x)**2/x", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"Substitute $u=\ln x$, $du=\frac{dx}{x}$",
               r"Integral becomes $\int u^2 du=\frac{\ln^3 x}{3}$"]},
    {"isrc": "sp.log(x)/x**2", "topic": "Inverse Trig & Log", "difficulty": "medium",
     "hints": [r"By parts: $u=\ln x$, $dv=x^{-2}dx$",
               r"Then $v=-\frac1x$"]},

    # ══ Radicals & Trig Substitution ═══════════════════════════════════════════
    {"isrc": "sp.sqrt(x**2+x+1)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Complete the square: $x^2+x+1=(x+\tfrac12)^2+\tfrac34$",
               r"Substitute $x+\tfrac12=\frac{\sqrt3}{2}\tan\theta$ (or use the $\sqrt{u^2+a^2}$ form)"]},
    {"isrc": "sp.sqrt(x**2-1)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=\sec\theta$, so $\sqrt{x^2-1}=\tan\theta$",
               r"Reduces to $\int\sec\theta\tan^2\theta\,d\theta$; or use the standard $\frac{x\sqrt{x^2-1}}{2}-\frac12\ln|x+\sqrt{x^2-1}|$"]},
    {"isrc": "sp.sqrt(x**2-4)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=2\sec\theta$",
               r"Then $\sqrt{x^2-4}=2\tan\theta$"]},
    {"isrc": "(1-x**2)**sp.Rational(3,2)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=\sin\theta$, so $(1-x^2)^{3/2}=\cos^3\theta$ and $dx=\cos\theta\,d\theta$",
               r"Integrate $\cos^4\theta$ via power reduction"]},
    {"isrc": "(x**2+1)**sp.Rational(3,2)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=\tan\theta$, so $(x^2+1)^{3/2}=\sec^3\theta$",
               r"Integrate $\sec^5\theta$ via reduction"]},
    {"isrc": "sp.sqrt(x)/(1+x)", "topic": "Radicals", "difficulty": "medium",
     "hints": [r"Substitute $u=\sqrt x$, $x=u^2$, $dx=2u\,du$",
               r"Reduces to $\int\frac{2u^2}{1+u^2}du$"]},
    {"isrc": "1/(sp.sqrt(x)*(1+x))", "topic": "Radicals", "difficulty": "medium",
     "hints": [r"Substitute $u=\sqrt x$, $dx=2u\,du$",
               r"Reduces to $\int\frac{2}{1+u^2}du=2\arctan\sqrt x$"]},

    # ══ Exponential Products (by parts / reappearing integral) ═════════════════
    {"isrc": "sp.exp(2*x)*sp.sin(3*x)", "topic": "Exponential Products", "difficulty": "hard",
     "hints": [r"By parts twice; the original integral reappears",
               r"Solve algebraically: $I=\frac{e^{2x}(2\sin 3x-3\cos 3x)}{13}$"]},
    {"isrc": "sp.exp(x)*sp.cos(2*x)", "topic": "Exponential Products", "difficulty": "hard",
     "hints": [r"By parts twice until $I$ returns on the right",
               r"Solve the resulting equation for $I$"]},
    {"isrc": "sp.exp(-x)*sp.sin(x)**2", "topic": "Exponential Products", "difficulty": "hard",
     "hints": [r"Use $\sin^2 x=\frac{1-\cos 2x}{2}$",
               r"Then integrate $e^{-x}$ and $e^{-x}\cos 2x$ separately"]},
    {"isrc": "x*sp.exp(x)*sp.sin(x)", "topic": "Exponential Products", "difficulty": "hard",
     "hints": [r"Combine the $x$ and the $e^x\sin x$ structure with parts",
               r"You'll need the known $\int e^x\sin x\,dx$ along the way"]},

    # ══ Definite — Famous Results ══════════════════════════════════════════════
    {"isrc": "sp.log(x)/(x-1)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(1)",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Expand $\frac{1}{1-x}=\sum x^n$ and integrate term by term",
               r"You get $\sum\frac{1}{(n+1)^2}=\frac{\pi^2}{6}$ (the Basel sum)"]},
    {"isrc": "sp.log(x)**2", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(1)",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Integrate by parts twice (the antiderivative is $x\ln^2 x-2x\ln x+2x$)",
               r"Evaluate the limit as $x\to0^+$ carefully"]},
    {"isrc": "sp.log(x)**3", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(1)",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Use $\int_0^1\ln^n x\,dx=(-1)^n n!$",
               r"Here $n=3$ gives $-6$"]},
    {"isrc": "sp.exp(-x**2)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"This is the Gaussian integral (half-line)",
               r"Square it and switch to polar coordinates to get $\frac{\sqrt\pi}{2}$"]},
    {"isrc": "sp.exp(-x**2)", "integral_type": "definite", "lsrc": "-sp.oo", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"The full Gaussian integral",
               r"$\left(\int_{-\infty}^{\infty}e^{-x^2}dx\right)^2=\int\int e^{-(x^2+y^2)}$ — polar coordinates give $\sqrt\pi$"]},
    {"isrc": "x**4*sp.exp(-x**2)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Relate to the Gamma function: $\int_0^\infty x^4 e^{-x^2}dx=\frac12\Gamma(\tfrac52)$",
               r"$\Gamma(\tfrac52)=\frac{3\sqrt\pi}{4}$"]},
    {"isrc": "x**3*sp.exp(-x**2)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "medium",
     "hints": [r"Substitute $u=x^2$, $du=2x\,dx$",
               r"Reduces to $\frac12\int_0^\infty u e^{-u}du=\frac12$"]},
    {"isrc": "sp.exp(-x**2)*sp.cos(x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Differentiate under the integral sign with a parameter, or complete the square in the exponent",
               r"The result is $\frac{\sqrt\pi}{2}e^{-1/4}$"]},
    {"isrc": "sp.sin(x)/x", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "trusted": True, "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"The Dirichlet integral",
               r"Use $\int_0^\infty\frac{\sin x}{x}dx=\int_0^\infty\int_0^\infty\sin x\,e^{-xt}\,dt\,dx$ (Feynman/Laplace)",
               r"The value is $\frac{\pi}{2}$"]},
    {"isrc": "sp.sin(x)**2/x**2", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "trusted": True, "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Integrate by parts to relate it to the Dirichlet integral $\int_0^\infty\frac{\sin x}{x}dx$",
               r"The value is also $\frac{\pi}{2}$"]},
    {"isrc": "1/(1+x**4)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Use the $\beta$-function / partial fractions, or contour ideas",
               r"$\int_0^\infty\frac{dx}{1+x^4}=\frac{\pi}{2\sqrt2}$"]},
    {"isrc": "x**2/(1+x**4)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"By symmetry $x\to1/x$ this equals $\int_0^\infty\frac{dx}{1+x^4}$",
               r"Both equal $\frac{\pi}{2\sqrt2}$"]},
    {"isrc": "1/(1+x**6)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Use $\int_0^\infty\frac{x^{s-1}}{1+x^n}dx=\frac{\pi/n}{\sin(\pi s/n)}$",
               r"Here $s=1$, $n=6$ gives $\frac{\pi}{3}$"]},
    {"isrc": "1/(1+x**3)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Use $\int_0^\infty\frac{dx}{1+x^n}=\frac{\pi/n}{\sin(\pi/n)}$",
               r"Here $n=3$ gives $\frac{2\pi}{3\sqrt3}$"]},
    {"isrc": "x/(1+x**4)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "medium",
     "hints": [r"Substitute $u=x^2$",
               r"Reduces to $\frac12\int_0^\infty\frac{du}{1+u^2}=\frac{\pi}{4}$"]},
    {"isrc": "x**4/(x**4-89*x**2+2025)**2", "integral_type": "definite", "lsrc": "-sp.oo", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"The denominator $x^4-89x^2+2025$ has no real roots (it's $(x^2-a)(x^2-b)$ with complex $a,b$)",
               r"Use residues / symmetry; the surprisingly clean value is $\frac{\pi}{2}$"]},
    {"isrc": "1/(x**2+1)**3", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Substitute $x=\tan\theta$: becomes $\int_0^{\pi/2}\cos^4\theta\,d\theta$",
               r"Wallis gives $\frac{3\pi}{16}$"]},
    {"isrc": "x**2/(x**2+1)**3", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Substitute $x=\tan\theta$: becomes $\int_0^{\pi/2}\sin^2\theta\cos^2\theta\,d\theta$",
               r"Equals $\frac{\pi}{16}$"]},
    {"isrc": "sp.sin(x)**6", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.pi/2",
     "topic": "Definite — Famous", "difficulty": "medium",
     "hints": [r"Wallis formula: $\int_0^{\pi/2}\sin^6 x\,dx=\frac{5\cdot3\cdot1}{6\cdot4\cdot2}\cdot\frac\pi2$",
               r"Equals $\frac{5\pi}{32}$"]},
    {"isrc": "sp.sin(x)**4*sp.cos(x)**2", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.pi/2",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Use the beta-function form $\int_0^{\pi/2}\sin^m x\cos^n x\,dx=\frac12 B(\tfrac{m+1}2,\tfrac{n+1}2)$",
               r"With $m=4,n=2$ this is $\frac{\pi}{32}$"]},
    {"isrc": "sp.sin(x)**2*sp.cos(x)**2", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "2*sp.pi",
     "topic": "Definite — Famous", "difficulty": "medium",
     "hints": [r"$\sin^2 x\cos^2 x=\frac14\sin^2 2x=\frac18(1-\cos 4x)$",
               r"Integrate over a full period to get $\frac{\pi}{4}$"]},
    {"isrc": "1/(2+sp.cos(x))", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "2*sp.pi",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Weierstrass over a full period, or the standard $\int_0^{2\pi}\frac{dx}{a+b\cos x}=\frac{2\pi}{\sqrt{a^2-b^2}}$",
               r"Here $a=2,b=1$ gives $\frac{2\pi}{\sqrt3}$"]},
    {"isrc": "1/(5+4*sp.sin(x))", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "2*sp.pi",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Use $\int_0^{2\pi}\frac{dx}{a+b\sin x}=\frac{2\pi}{\sqrt{a^2-b^2}}$",
               r"Here $a=5,b=4$ gives $\frac{2\pi}{3}$"]},
    {"isrc": "x**2*sp.exp(-x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "medium",
     "hints": [r"$\int_0^\infty x^n e^{-x}dx=n!=\Gamma(n+1)$",
               r"Here $n=2$ gives $2$"]},
    {"isrc": "sp.exp(-x)*sp.sin(x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Definite — Famous", "difficulty": "medium",
     "hints": [r"This is a Laplace transform of $\sin x$ at $s=1$",
               r"$\int_0^\infty e^{-x}\sin x\,dx=\frac{1}{1^2+1^2}=\frac12$"]},
    {"isrc": "sp.sin(x)*sp.sin(2*x)*sp.sin(3*x)*sp.sin(4*x)", "integral_type": "definite",
     "lsrc": "sp.Integer(0)", "usrc": "sp.pi/2",
     "topic": "Definite — Famous", "difficulty": "hard",
     "hints": [r"Convert products of sines to sums via product-to-sum identities",
               r"Most terms integrate to zero over $[0,\pi/2]$; the survivor gives $\frac{\pi}{16}$"]},
]
