"""
Candidate pool for the generator. Each entry's `isrc` is a source string in `x`
and `sp` (SymPy); the generator evals it to verify and emits it verbatim.

Bounds for definite integrals are also source strings (`lsrc`, `usrc`).
Integrands of the existing 20 registry problems are intentionally omitted.
"""

CANDIDATES: list[dict] = [
    # ── Power Rule / Basic Algebraic ──────────────────────────────────────────
    {"isrc": "x**5", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Apply the power rule: $\int x^n dx = \frac{x^{n+1}}{n+1}+C$",
               r"Here $n=5$"]},
    {"isrc": "x**7", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Power rule: raise the exponent by one and divide",
               r"$\int x^7 dx = \frac{x^8}{8}+C$"]},
    {"isrc": "1/x**2", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Rewrite $\frac{1}{x^2}=x^{-2}$",
               r"Apply the power rule with $n=-2$"]},
    {"isrc": "1/x**3", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Rewrite $\frac{1}{x^3}=x^{-3}$",
               r"Power rule with $n=-3$ gives $-\frac{1}{2x^2}$"]},
    {"isrc": "sp.sqrt(x)", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Rewrite $\sqrt{x}=x^{1/2}$",
               r"Power rule with $n=\frac{1}{2}$"]},
    {"isrc": "1/sp.sqrt(x)", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Rewrite $\frac{1}{\sqrt{x}}=x^{-1/2}$",
               r"Power rule gives $2\sqrt{x}$"]},
    {"isrc": "x**sp.Rational(1,3)", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Cube root is $x^{1/3}$",
               r"Power rule with $n=\frac{1}{3}$"]},
    {"isrc": "3*x**2 - 2*x + 1", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Integrate term by term",
               r"Each term follows the power rule"]},
    {"isrc": "x**4 + 3*x**2", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Split the sum and integrate each power separately"]},
    {"isrc": "(x + 1)**2", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Expand the square first, then integrate term by term",
               r"$(x+1)^2 = x^2+2x+1$"]},
    {"isrc": "x**sp.Rational(2,3)", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Apply the power rule with $n=\frac{2}{3}$"]},
    {"isrc": "4*x**3 - x", "topic": "Power Rule", "difficulty": "easy",
     "hints": [r"Integrate term by term using the power rule"]},

    # ── Exponential & Logarithmic ─────────────────────────────────────────────
    {"isrc": "sp.exp(3*x)", "topic": "Exponential", "difficulty": "easy",
     "hints": [r"$\int e^{ax}dx = \frac{1}{a}e^{ax}+C$",
               r"Here $a=3$"]},
    {"isrc": "sp.exp(-x)", "topic": "Exponential", "difficulty": "easy",
     "hints": [r"$\int e^{-x}dx = -e^{-x}+C$"]},
    {"isrc": "sp.exp(x/2)", "topic": "Exponential", "difficulty": "easy",
     "hints": [r"$\int e^{ax}dx=\frac{1}{a}e^{ax}$ with $a=\frac{1}{2}$"]},
    {"isrc": "2**x", "topic": "Exponential", "difficulty": "medium",
     "hints": [r"$\int a^x dx = \frac{a^x}{\ln a}+C$",
               r"Here $a=2$"]},
    {"isrc": "5**x", "topic": "Exponential", "difficulty": "medium",
     "hints": [r"Use $\int a^x dx=\frac{a^x}{\ln a}+C$ with $a=5$"]},
    {"isrc": "sp.exp(x) + x", "topic": "Exponential", "difficulty": "easy",
     "hints": [r"Integrate $e^x$ and $x$ separately"]},
    {"isrc": "1/x", "topic": "Logarithmic", "difficulty": "easy",
     "hints": [r"$\int \frac{1}{x}dx=\ln|x|+C$"]},
    {"isrc": "1/(2*x)", "topic": "Logarithmic", "difficulty": "easy",
     "hints": [r"Factor out $\frac{1}{2}$, then integrate $\frac{1}{x}$"]},
    {"isrc": "3/x + 2*x", "topic": "Logarithmic", "difficulty": "easy",
     "hints": [r"$\frac{3}{x}$ integrates to $3\ln|x|$; the other term by power rule"]},

    # ── Basic Trigonometric ───────────────────────────────────────────────────
    {"isrc": "sp.sin(x)", "topic": "Trigonometric", "difficulty": "easy",
     "hints": [r"$\int \sin(x)dx=-\cos(x)+C$"]},
    {"isrc": "sp.cos(3*x)", "topic": "Trigonometric", "difficulty": "easy",
     "hints": [r"$\int \cos(ax)dx=\frac{1}{a}\sin(ax)+C$ with $a=3$"]},
    {"isrc": "sp.sin(2*x)", "topic": "Trigonometric", "difficulty": "easy",
     "hints": [r"$\int \sin(ax)dx=-\frac{1}{a}\cos(ax)+C$ with $a=2$"]},
    {"isrc": "sp.sec(x)**2", "topic": "Trigonometric", "difficulty": "easy",
     "hints": [r"Recognize the derivative of $\tan(x)$",
               r"$\int \sec^2(x)dx=\tan(x)+C$"]},
    {"isrc": "sp.csc(x)**2", "topic": "Trigonometric", "difficulty": "easy",
     "hints": [r"This is the derivative of $-\cot(x)$"]},
    {"isrc": "sp.sec(x)*sp.tan(x)", "topic": "Trigonometric", "difficulty": "easy",
     "hints": [r"Recognize the derivative of $\sec(x)$"]},
    {"isrc": "sp.tan(x)", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Write $\tan(x)=\frac{\sin(x)}{\cos(x)}$",
               r"Substitute $u=\cos(x)$, $du=-\sin(x)dx$"]},
    {"isrc": "sp.cot(x)", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Write $\cot(x)=\frac{\cos(x)}{\sin(x)}$",
               r"Substitute $u=\sin(x)$"]},
    {"isrc": "sp.cos(x)**2", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Use the power-reduction identity $\cos^2(x)=\frac{1+\cos(2x)}{2}$",
               r"Integrate term by term"]},
    {"isrc": "sp.sin(x)**2", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\sin^2(x)=\frac{1-\cos(2x)}{2}$",
               r"Integrate term by term"]},
    {"isrc": "sp.cos(x)**3", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Write $\cos^3(x)=\cos(x)(1-\sin^2(x))$",
               r"Substitute $u=\sin(x)$"]},
    {"isrc": "sp.sin(x)*sp.cos(x)", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Substitute $u=\sin(x)$, $du=\cos(x)dx$",
               r"Or use $\sin(x)\cos(x)=\frac{1}{2}\sin(2x)$"]},
    {"isrc": "sp.sin(x)**2*sp.cos(x)", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Substitute $u=\sin(x)$, $du=\cos(x)dx$",
               r"Integrate $u^2$"]},
    {"isrc": "sp.tan(x)**2", "topic": "Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\tan^2(x)=\sec^2(x)-1$",
               r"Integrate each term"]},

    # ── Substitution ──────────────────────────────────────────────────────────
    {"isrc": "2*x*sp.exp(x**2)", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=x^2$, $du=2x\,dx$",
               r"The integral becomes $\int e^u du$"]},
    {"isrc": "x/(x**2+1)", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=x^2+1$, $du=2x\,dx$",
               r"You get $\frac{1}{2}\ln(x^2+1)$"]},
    {"isrc": "x**2/(x**3+1)", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=x^3+1$, $du=3x^2 dx$"]},
    {"isrc": "sp.cos(x)*sp.exp(sp.sin(x))", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=\sin(x)$, $du=\cos(x)dx$",
               r"The integral becomes $\int e^u du$"]},
    {"isrc": "x*sp.sqrt(x**2+1)", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=x^2+1$, $du=2x\,dx$",
               r"Integrate $\frac{1}{2}\sqrt{u}$"]},
    {"isrc": "x/sp.sqrt(x**2+1)", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=x^2+1$; the $x\,dx$ matches $\frac{1}{2}du$"]},
    {"isrc": "sp.log(x)/x", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=\ln(x)$, $du=\frac{1}{x}dx$",
               r"Integrate $u$"]},
    {"isrc": "1/(x*sp.log(x))", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=\ln(x)$, $du=\frac{1}{x}dx$",
               r"You get $\ln|\ln(x)|$"]},
    {"isrc": "sp.exp(x)/(1+sp.exp(x))", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=1+e^x$, $du=e^x dx$",
               r"You get $\ln(1+e^x)$"]},
    {"isrc": "(2*x+3)**5", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=2x+3$, $du=2\,dx$",
               r"Integrate $\frac{1}{2}u^5$"]},
    {"isrc": "sp.sin(x)/sp.cos(x)**2", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=\cos(x)$, $du=-\sin(x)dx$",
               r"Integrate $-u^{-2}$"]},
    {"isrc": "x*sp.exp(-x**2)", "topic": "Substitution", "difficulty": "medium",
     "hints": [r"Let $u=-x^2$, $du=-2x\,dx$",
               r"The integral becomes $-\frac{1}{2}\int e^u du$"]},

    # ── Integration by Parts ──────────────────────────────────────────────────
    {"isrc": "x*sp.exp(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=x$, $dv=e^x dx$",
               r"Then $du=dx$, $v=e^x$"]},
    {"isrc": "x*sp.sin(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=x$, $dv=\sin(x)dx$",
               r"Then $v=-\cos(x)$"]},
    {"isrc": "x*sp.cos(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=x$, $dv=\cos(x)dx$",
               r"Then $v=\sin(x)$"]},
    {"isrc": "x**2*sp.exp(x)", "topic": "Integration by Parts", "difficulty": "hard",
     "hints": [r"Let $u=x^2$, $dv=e^x dx$",
               r"Apply parts twice to reduce the power of $x$"]},
    {"isrc": "sp.log(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=\ln(x)$, $dv=dx$",
               r"Then $du=\frac{1}{x}dx$, $v=x$; result is $x\ln(x)-x$"]},
    {"isrc": "x*sp.log(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=\ln(x)$, $dv=x\,dx$",
               r"Then $v=\frac{x^2}{2}$"]},
    {"isrc": "x**3*sp.log(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=\ln(x)$, $dv=x^3 dx$",
               r"Then $v=\frac{x^4}{4}$"]},
    {"isrc": "sp.exp(x)*sp.cos(x)", "topic": "Integration by Parts", "difficulty": "hard",
     "hints": [r"Apply parts twice until the original integral reappears",
               r"Solve algebraically for the integral"]},
    {"isrc": "sp.exp(x)*sp.sin(x)", "topic": "Integration by Parts", "difficulty": "hard",
     "hints": [r"Apply parts twice; the original integral returns",
               r"Solve algebraically for $I$"]},
    {"isrc": "sp.atan(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=\arctan(x)$, $dv=dx$",
               r"Then $du=\frac{1}{1+x^2}dx$, $v=x$"]},
    {"isrc": "x*sp.exp(2*x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=x$, $dv=e^{2x}dx$",
               r"Then $v=\frac{1}{2}e^{2x}$"]},
    {"isrc": "sp.acos(x)", "topic": "Integration by Parts", "difficulty": "medium",
     "hints": [r"Let $u=\arccos(x)$, $dv=dx$",
               r"Then $du=-\frac{1}{\sqrt{1-x^2}}dx$, $v=x$"]},

    # ── Inverse Trig Forms / 1 over Quadratic ─────────────────────────────────
    {"isrc": "1/(x**2+1)", "topic": "Inverse Trigonometric", "difficulty": "easy",
     "hints": [r"Recognize $\int\frac{1}{1+x^2}dx=\arctan(x)+C$"]},
    {"isrc": "1/(x**2+9)", "topic": "Inverse Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\int\frac{1}{x^2+a^2}dx=\frac{1}{a}\arctan\frac{x}{a}$",
               r"Here $a=3$"]},
    {"isrc": "1/(x**2+4)", "topic": "Inverse Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\frac{1}{a}\arctan\frac{x}{a}$ with $a=2$"]},
    {"isrc": "1/sp.sqrt(1-x**2)", "topic": "Inverse Trigonometric", "difficulty": "medium",
     "hints": [r"Recognize $\int\frac{1}{\sqrt{1-x^2}}dx=\arcsin(x)+C$"]},
    {"isrc": "1/sp.sqrt(4-x**2)", "topic": "Inverse Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\int\frac{1}{\sqrt{a^2-x^2}}dx=\arcsin\frac{x}{a}$ with $a=2$"]},
    {"isrc": "1/sp.sqrt(9-x**2)", "topic": "Inverse Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\arcsin\frac{x}{a}$ with $a=3$"]},
    {"isrc": "1/(1+4*x**2)", "topic": "Inverse Trigonometric", "difficulty": "medium",
     "hints": [r"Factor: $\frac{1}{1+(2x)^2}$",
               r"Substitute $u=2x$"]},

    # ── Partial Fractions ─────────────────────────────────────────────────────
    {"isrc": "1/(x*(x+1))", "topic": "Partial Fractions", "difficulty": "medium",
     "hints": [r"Decompose $\frac{1}{x(x+1)}=\frac{1}{x}-\frac{1}{x+1}$",
               r"Integrate each logarithm"]},
    {"isrc": "1/((x-1)*(x+2))", "topic": "Partial Fractions", "difficulty": "medium",
     "hints": [r"Write $\frac{A}{x-1}+\frac{B}{x+2}$ and solve for $A,B$"]},
    {"isrc": "1/(x**2-4)", "topic": "Partial Fractions", "difficulty": "medium",
     "hints": [r"Factor $x^2-4=(x-2)(x+2)$",
               r"Decompose into partial fractions"]},
    {"isrc": "1/(x**2+5*x+6)", "topic": "Partial Fractions", "difficulty": "medium",
     "hints": [r"Factor $x^2+5x+6=(x+2)(x+3)$",
               r"Decompose and integrate"]},
    {"isrc": "x/((x+1)*(x+2))", "topic": "Partial Fractions", "difficulty": "medium",
     "hints": [r"Write $\frac{A}{x+1}+\frac{B}{x+2}$",
               r"Solve for $A,B$ then integrate"]},
    {"isrc": "1/(x**3+x)", "topic": "Partial Fractions", "difficulty": "hard",
     "hints": [r"Factor $x^3+x=x(x^2+1)$",
               r"Decompose into $\frac{A}{x}+\frac{Bx+C}{x^2+1}$"]},
    {"isrc": "(2*x+1)/(x**2+x-2)", "topic": "Partial Fractions", "difficulty": "hard",
     "hints": [r"Factor the denominator $x^2+x-2=(x+2)(x-1)$",
               r"Decompose and integrate to logarithms"]},
    {"isrc": "1/(x**2-9)", "topic": "Partial Fractions", "difficulty": "medium",
     "hints": [r"Factor $(x-3)(x+3)$ and decompose"]},

    # ── Completing the Square ─────────────────────────────────────────────────
    {"isrc": "1/(x**2+4*x+5)", "topic": "Completing the Square", "difficulty": "medium",
     "hints": [r"Complete the square: $x^2+4x+5=(x+2)^2+1$",
               r"Use the arctan form"]},
    {"isrc": "1/(x**2-2*x+5)", "topic": "Completing the Square", "difficulty": "medium",
     "hints": [r"Complete the square: $(x-1)^2+4$",
               r"Then $\frac{1}{a}\arctan\frac{u}{a}$ with $a=2$"]},
    {"isrc": "1/(x**2+6*x+13)", "topic": "Completing the Square", "difficulty": "medium",
     "hints": [r"Complete the square: $(x+3)^2+4$",
               r"Apply the arctan formula"]},
    {"isrc": "1/sp.sqrt(-x**2+4*x)", "topic": "Completing the Square", "difficulty": "hard",
     "hints": [r"Complete the square under the root: $4-(x-2)^2$",
               r"Use the arcsin form"]},

    # ── Trigonometric Substitution / Radicals ─────────────────────────────────
    {"isrc": "sp.sqrt(4-x**2)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=2\sin\theta$",
               r"Then $\sqrt{4-x^2}=2\cos\theta$ and integrate $\cos^2$"]},
    {"isrc": "sp.sqrt(9-x**2)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=3\sin\theta$",
               r"Reduce to $\int\cos^2\theta\,d\theta$"]},
    {"isrc": "sp.sqrt(x**2+1)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=\tan\theta$, $dx=\sec^2\theta\,d\theta$",
               r"Then $\sqrt{x^2+1}=\sec\theta$; integrate $\sec^3\theta$"]},
    {"isrc": "1/sp.sqrt(x**2+1)", "topic": "Trigonometric Substitution", "difficulty": "medium",
     "hints": [r"Let $x=\tan\theta$ or recognize the $\operatorname{arcsinh}$ form",
               r"Result is $\ln(x+\sqrt{x^2+1})$"]},
    {"isrc": "x**2/sp.sqrt(1-x**2)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=\sin\theta$",
               r"Reduce to $\int\sin^2\theta\,d\theta$"]},
    {"isrc": "1/sp.sqrt(x**2-1)", "topic": "Trigonometric Substitution", "difficulty": "hard",
     "hints": [r"Let $x=\sec\theta$",
               r"Result is $\ln|x+\sqrt{x^2-1}|$"]},

    # ── Hyperbolic ────────────────────────────────────────────────────────────
    {"isrc": "sp.sinh(x)", "topic": "Hyperbolic", "difficulty": "easy",
     "hints": [r"$\int \sinh(x)dx=\cosh(x)+C$"]},
    {"isrc": "sp.cosh(x)", "topic": "Hyperbolic", "difficulty": "easy",
     "hints": [r"$\int \cosh(x)dx=\sinh(x)+C$"]},
    {"isrc": "sp.tanh(x)", "topic": "Hyperbolic", "difficulty": "medium",
     "hints": [r"Write $\tanh(x)=\frac{\sinh(x)}{\cosh(x)}$",
               r"Substitute $u=\cosh(x)$; result is $\ln(\cosh(x))$"]},
    {"isrc": "x*sp.cosh(x)", "topic": "Hyperbolic", "difficulty": "medium",
     "hints": [r"Integration by parts: $u=x$, $dv=\cosh(x)dx$",
               r"Then $v=\sinh(x)$"]},
    {"isrc": "sp.sinh(x)**2", "topic": "Hyperbolic", "difficulty": "medium",
     "hints": [r"Use $\sinh^2(x)=\frac{\cosh(2x)-1}{2}$",
               r"Integrate term by term"]},

    # ── Rational / Algebraic Manipulation ─────────────────────────────────────
    {"isrc": "(x**2+1)/x", "topic": "Rational Functions", "difficulty": "easy",
     "hints": [r"Split: $\frac{x^2+1}{x}=x+\frac{1}{x}$",
               r"Integrate each term"]},
    {"isrc": "(x+1)/(x-1)", "topic": "Rational Functions", "difficulty": "medium",
     "hints": [r"Divide: $\frac{x+1}{x-1}=1+\frac{2}{x-1}$",
               r"Integrate each term"]},
    {"isrc": "x**3/(x**2+1)", "topic": "Rational Functions", "difficulty": "medium",
     "hints": [r"Polynomial division: $\frac{x^3}{x^2+1}=x-\frac{x}{x^2+1}$",
               r"Integrate each piece"]},
    {"isrc": "x**2/(x**2+1)", "topic": "Rational Functions", "difficulty": "medium",
     "hints": [r"Rewrite $\frac{x^2}{x^2+1}=1-\frac{1}{x^2+1}$",
               r"Integrate to $x-\arctan(x)$"]},
    {"isrc": "(x**3+x+1)/x", "topic": "Rational Functions", "difficulty": "easy",
     "hints": [r"Divide each term by $x$, then integrate term by term"]},

    # ── Definite Integrals ────────────────────────────────────────────────────
    {"isrc": "x**2", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(1)",
     "topic": "Definite", "difficulty": "easy",
     "hints": [r"Antiderivative is $\frac{x^3}{3}$",
               r"Evaluate from $0$ to $1$"]},
    {"isrc": "x**3", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(2)",
     "topic": "Definite", "difficulty": "easy",
     "hints": [r"Antiderivative is $\frac{x^4}{4}$",
               r"Evaluate at the bounds"]},
    {"isrc": "sp.sin(x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.pi",
     "topic": "Definite", "difficulty": "easy",
     "hints": [r"Antiderivative is $-\cos(x)$",
               r"$-\cos(\pi)+\cos(0)=2$"]},
    {"isrc": "sp.cos(x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.pi/2",
     "topic": "Definite", "difficulty": "easy",
     "hints": [r"Antiderivative is $\sin(x)$",
               r"Evaluate from $0$ to $\frac{\pi}{2}$"]},
    {"isrc": "sp.exp(x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(1)",
     "topic": "Definite", "difficulty": "easy",
     "hints": [r"Antiderivative is $e^x$",
               r"Result is $e-1$"]},
    {"isrc": "1/x", "integral_type": "definite", "lsrc": "sp.Integer(1)", "usrc": "sp.E",
     "topic": "Definite", "difficulty": "medium",
     "hints": [r"Antiderivative is $\ln(x)$",
               r"$\ln(e)-\ln(1)=1$"]},
    {"isrc": "1/(1+x**2)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(1)",
     "topic": "Definite", "difficulty": "medium",
     "hints": [r"Antiderivative is $\arctan(x)$",
               r"$\arctan(1)-\arctan(0)=\frac{\pi}{4}$"]},
    {"isrc": "sp.sqrt(x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(4)",
     "topic": "Definite", "difficulty": "easy",
     "hints": [r"Antiderivative is $\frac{2}{3}x^{3/2}$",
               r"Evaluate at $4$"]},
    {"isrc": "x*sp.exp(x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.Integer(1)",
     "topic": "Definite", "difficulty": "medium",
     "hints": [r"Integrate by parts to get $(x-1)e^x$",
               r"Evaluate from $0$ to $1$"]},
    {"isrc": "sp.sin(x)**2", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.pi",
     "topic": "Definite Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\sin^2(x)=\frac{1-\cos(2x)}{2}$",
               r"Integrate over $[0,\pi]$"]},
    {"isrc": "x**2", "integral_type": "definite", "lsrc": "sp.Integer(-1)", "usrc": "sp.Integer(1)",
     "topic": "Definite", "difficulty": "easy",
     "hints": [r"Even function; antiderivative $\frac{x^3}{3}$",
               r"Evaluate symmetric bounds"]},
    {"isrc": "sp.cos(x)**2", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.pi",
     "topic": "Definite Trigonometric", "difficulty": "medium",
     "hints": [r"Use $\cos^2(x)=\frac{1+\cos(2x)}{2}$",
               r"Integrate over $[0,\pi]$"]},

    # ── Improper Integrals ────────────────────────────────────────────────────
    {"isrc": "1/x**2", "integral_type": "definite", "lsrc": "sp.Integer(1)", "usrc": "sp.oo",
     "topic": "Improper Integral", "difficulty": "medium",
     "hints": [r"Antiderivative is $-\frac{1}{x}$",
               r"Take the limit as the upper bound $\to\infty$"]},
    {"isrc": "sp.exp(-x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Improper Integral", "difficulty": "medium",
     "hints": [r"Antiderivative is $-e^{-x}$",
               r"As $x\to\infty$, $e^{-x}\to 0$; result is $1$"]},
    {"isrc": "sp.exp(-2*x)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Improper Integral", "difficulty": "medium",
     "hints": [r"Antiderivative is $-\frac{1}{2}e^{-2x}$",
               r"Evaluate the limit; result is $\frac{1}{2}$"]},
    {"isrc": "x*sp.exp(-x**2)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Improper Integral", "difficulty": "hard",
     "hints": [r"Substitute $u=x^2$",
               r"The integral becomes $\frac{1}{2}\int_0^\infty e^{-u}du=\frac{1}{2}$"]},
    {"isrc": "1/x**3", "integral_type": "definite", "lsrc": "sp.Integer(1)", "usrc": "sp.oo",
     "topic": "Improper Integral", "difficulty": "medium",
     "hints": [r"Antiderivative is $-\frac{1}{2x^2}$",
               r"Take the limit at infinity"]},
    {"isrc": "1/(x**2+1)", "integral_type": "definite", "lsrc": "sp.Integer(0)", "usrc": "sp.oo",
     "topic": "Improper Integral", "difficulty": "hard",
     "hints": [r"Antiderivative is $\arctan(x)$",
               r"As $x\to\infty$, $\arctan(x)\to\frac{\pi}{2}$"]},
]
